/**
 * reportGenerator.js
 * Generates a clean PDF shortlist report using PDFKit.
 */

const PDFDocument = require("pdfkit");
const { WEIGHTS, HIRE_THRESHOLD } = require("../services/rankEngine");

const DIMENSION_LABELS = {
  skills_match: "Skills Match",
  experience_relevance: "Experience Relevance",
  education: "Education & Certifications",
  projects: "Project / Portfolio",
  communication: "Communication Quality",
};

/**
 * Generate a PDF buffer for a job shortlist.
 * @param {Object} job - Job document
 * @param {Array} candidates - Sorted candidate documents
 * @returns {Promise<Buffer>}
 */
const generatePDF = (job, candidates) => {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: "A4" });
    const buffers = [];

    doc.on("data", (chunk) => buffers.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(buffers)));
    doc.on("error", reject);

    // ── Cover header ──────────────────────────────────────────
    doc.fontSize(20).font("Helvetica-Bold").text("HR Shortlist Report", { align: "center" });
    doc.moveDown(0.5);
    doc.fontSize(13).font("Helvetica").text(`Role: ${job.title}`, { align: "center" });
    doc.fontSize(10).fillColor("gray")
      .text(`Generated: ${new Date().toLocaleString()}  |  Candidates evaluated: ${candidates.length}  |  Hire threshold: ${HIRE_THRESHOLD}/10`, { align: "center" });
    doc.fillColor("black");
    doc.moveDown(1);
    doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke();
    doc.moveDown(1);

    // ── JD Summary ───────────────────────────────────────────
    if (job.parsed_jd) {
      doc.fontSize(12).font("Helvetica-Bold").text("Job Requirements Summary");
      doc.moveDown(0.3);
      doc.fontSize(10).font("Helvetica");
      doc.text(`Domain: ${job.parsed_jd.domain || "N/A"}`);
      doc.text(`Min Experience: ${job.parsed_jd.experience_years || 0} years`);
      doc.text(`Education: ${job.parsed_jd.education || "N/A"}`);
      doc.text(`Required Skills: ${(job.parsed_jd.skills || []).join(", ") || "N/A"}`);
      doc.moveDown(1);
      doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke("#cccccc");
      doc.moveDown(1);
    }

    // ── Candidates ───────────────────────────────────────────
    candidates.forEach((candidate, index) => {
      // Page break for candidates after the first (roughly)
      if (doc.y > 650) doc.addPage();

      const isHire = candidate.recommendation === "hire";

      // Rank + name header
      doc.fontSize(13).font("Helvetica-Bold")
        .text(`#${index + 1}  ${candidate.parsed_profile?.name || "Unknown Candidate"}`, { continued: true })
        .fontSize(11).font("Helvetica")
        .fillColor(isHire ? "green" : "red")
        .text(`   ${isHire ? "✓ HIRE" : "✗ NO-HIRE"}   Total: ${candidate.total_score}/10`)
        .fillColor("black");

      doc.moveDown(0.4);
      doc.fontSize(10).font("Helvetica");
      doc.text(`Experience: ${candidate.parsed_profile?.experience_years || 0} yrs  |  Education: ${candidate.parsed_profile?.education || "N/A"}`);

      if (candidate.parsed_profile?.skills?.length) {
        doc.text(`Skills: ${candidate.parsed_profile.skills.slice(0, 10).join(", ")}`);
      }

      doc.moveDown(0.5);
      doc.fontSize(10).font("Helvetica-Bold").text("Dimension Scores:");
      doc.font("Helvetica");
      doc.moveDown(0.2);

      for (const [dim, label] of Object.entries(DIMENSION_LABELS)) {
        const d = candidate.scores?.[dim];
        if (!d) continue;
        const weightPct = Math.round(WEIGHTS[dim] * 100);
        const weighted = ((d.score * WEIGHTS[dim]).toFixed(2));
        doc.text(`  ${label} (${weightPct}%): ${d.score}/10  [weighted: ${weighted}]`);
        doc.fontSize(9).fillColor("#555555").text(`    → ${d.justification}`).fillColor("black").fontSize(10);
      }

      // Overrides
      if (candidate.overrides?.length > 0) {
        doc.moveDown(0.4);
        doc.font("Helvetica-Bold").text("HR Overrides:");
        doc.font("Helvetica");
        candidate.overrides.forEach((o) => {
          doc.fontSize(9).fillColor("#885500")
            .text(`  • ${DIMENSION_LABELS[o.dimension] || o.dimension}: ${o.original_score} → ${o.new_score} — "${o.reason}"`)
            .fillColor("black").fontSize(10);
        });
      }

      doc.moveDown(1);
      doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke("#eeeeee");
      doc.moveDown(1);
    });

    // ── Footer ────────────────────────────────────────────────
    doc.fontSize(9).fillColor("gray")
      .text("This report was generated by HR Resume Shortlisting Agent. Human review required for final decisions.", 50, doc.page.height - 60, { align: "center", width: 495 });

    doc.end();
  });
};

module.exports = { generatePDF };
